/**
 * Copies per-profile icon.png / splash.png / Firebase config into the
 * profile's native folder ONLY. Never touches other profiles.
 * Skips gracefully if source assets or native folder are missing.
 */
import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { activeProfile } from "./_profileUtils";

const p = activeProfile();

function safeCopy(src: string, dest: string, label: string) {
  if (!existsSync(src)) {
    console.log(`[assets] Skip ${label}: ${src} missing`);
    return;
  }
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(src, dest);
  console.log(`[assets] Copied ${label}: ${src} → ${dest}`);
}

// iOS asset catalogue (icons + splash are generated by generate-app-icons.ts
// and generate-splash.ts, run right after this script in build-app.ts).
safeCopy(p.iconPath, join(p.resourcesDir, ".icon-source.png"), "icon source");
safeCopy(p.splashPath, join(p.resourcesDir, ".splash-source.png"), "splash source");

// Android Firebase config
if (p.push.fcmConfigPath) {
  const androidApp = join(p.androidDir, "app");
  if (existsSync(androidApp)) {
    safeCopy(p.push.fcmConfigPath, join(androidApp, "google-services.json"), "FCM config");
  }
}

console.log(`✓ sync-assets done for profile "${p.id}"`);
